# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45abd914517ad603315527ecb964124d8d571a31b373c5b577c777aeb9ebcecbfcc89ee51797f1124c4c898e108ae35563871ae937f238dc70b7c0097193fcca

test:
  secret_key_base: 2ef92fca9400e1e7c3b19abaae107c978f01c9f031e8627691aff48fec27a63de0ebf4bc16a576222a556e16f615bed0505fb9e842c022b7bebe81cc13dbae1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
